version: 2.1
jobs:
  build:
    docker:
      - image: circleci/gilang:1.15
        auth:
          username: mdsn
          password: $DOCKERHUB_PASSWORD
    step:
      - checkout

      - setup_remote_docker:
          version: 19.03.13

      - run:
          TAG=0.1.$CIRCLE_BUILD_NUM
          docker build -t mdsn/circleci-demo-docker:$TAG .
          docker login -u mdsn -p $DOCKERHUB_PASSWORD
          docker push mdsn/circleci-demodocker:$TAG